### ISSUE TITLE
Protocol buffer 2.2.0 does not build on Mac 10.5.8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [runt18/metasyntactic#117]
```
Steps :
1) Get protobuf-2.2.0 
svn checkout http://metasyntactic.googlecode.com/svn/trunk/protobuf-2.2.0
metasyntactic

2) ./configure

3) make

4) Notice this error

d.o java_extension.o java_field.o java_file.o java_generator.o
java_helpers.o java_message.o java_message_field.o java_primitive_field.o
java_service.o python_generator.o
libtool: link: ranlib .libs/libprotoc.a
libtool: link: ( cd ".libs" && rm -f "libprotoc.la" && ln -s
"../libprotoc.la" "libprotoc.la" )
/bin/sh ../libtool --tag=CXX   --mode=link g++ -D_THREAD_SAFE  -Wall
-Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG
-D_THREAD_SAFE   -o protoc main.o  libprotobuf.la libprotoc.la -lz 
libtool: link: g++ -D_THREAD_SAFE -Wall -Wwrite-strings
-Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -D_THREAD_SAFE -o
.libs/protoc main.o -Wl,-bind_at_load  ./.libs/libprotobuf.dylib
./.libs/libprotoc.dylib
/Users/epocratesuser/Dev/metasyntactic/src/.libs/libprotobuf.dylib -lz
Undefined symbols:

"google::protobuf::compiler::objectivec::ObjectiveCGenerator::~ObjectiveCGenerat
or()",
referenced from:
      _main in main.o
      _main in main.o

"google::protobuf::compiler::objectivec::ObjectiveCGenerator::ObjectiveCGenerato
r()",
referenced from:
      _main in main.o
ld: symbol(s) not found
collect2: ld returned 1 exit status
make[2]: *** [protoc] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

Original issue reported on code.google.com by `madha...@gmail.com` on 17 Sep 2009 at 8:23
